### ISSUE TITLE
前端部分部署

### ISSUE THREAD

**Issue by zK0G0w** [Chaobk/CBlog#1]
hello,我在部署naccl的博客项目前端部分的时候遇到一些疑问，因为我没有怎么接触过前端部署，方便请教一下嘛~

**Comment by Chaobk** [comment]
hello，当然可以，如果我会的话。
不过前端我也只是勉强够用，不知道能不能解答你的问题。
可以加一下我的qq，方便发一些图片啥的。




1004945427
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chaobk/CBlog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月18日(星期四) 下午3:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Chaobk/CBlog] 前端部分部署 (Issue #1)





 
hello,我在部署naccl的博客项目前端部分的时候遇到一些疑问，因为我没有怎么接触过前端部署，方便请教一下嘛~
